### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by wusj521** [SimonWaldherr/saprfc#1]
go run usr01.go
Environment: OS is WIN7 32BIT
Error message:
Michael@WAUA-PC MINGW32 /c/mygotest/saprfc-master/example (master)
$ go run usr01.go
go build simonwaldherr.de/go/saprfc: no buildable Go source files in C:\mygotest\src\simonwaldherr.de\go\saprfc

Is it a CGO problem? How to solve it? Thank you!

**Comment by wusj521** [comment]
Solved
Environment: OS is WIN7 64BIT

**Comment by SimonWaldherr** [comment]
@wusj521 please provide some info about the problem and how you solved it - to help others
